# 应用名称
spring:
  application:
    name: StudentSystem
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/stuSystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
# 应用服务 WEB 访问端口
server:
  port: 8080


#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录
#mybatis.type-aliases-package=com.example.studentsystem.mybatis.entity


